//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomelessDogs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public int Id_dog { get; set; }
        public Nullable<int> Id_aviary { get; set; }
        public Nullable<int> Id_gender { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Description { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> IsDie { get; set; }
        public Nullable<bool> IsGive { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Aviary Aviary { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
